package com.tarun.kahani;

/** v33: twenty simple stories for the soak test — ten short, ten long, in Hindi, English and Hinglish, cast from the user's sheets. */
final class SoakStories {
    private SoakStories() {}

    static final String HI_CAST = "पात्र:\n1. मीना (8 वर्ष): लड़की, सफ़ेद-नीला कुर्ता, दो चोटियाँ, कंधे पर झोला\n2. राजू बंदर: लाल-भूरे बालों वाला छोटा बंदर, लाल बंडी\n3. खान राक्षस: भीमकाय काले बालों वाला सींगों वाला राक्षस (monster), जंजीरें और हड्डियाँ\n"
            + "स्थान:\n1. महल का बगीचा: फूलों और तितलियों वाला बड़ा बगीचा\n2. गुफा: पहाड़ की गुफा, दरवाज़े पर पीतल का घंटा\n";
    static final String EN_CAST = "Characters:\n1. Asha (10 years): a brave girl, turquoise lehenga-choli, a long braid, a sword on her belt\n2. Khan: a huge black-furred horned monster (राक्षस) with chains and bones\n3. Raju: a small red-brown monkey (बंदर) in a red jacket\n"
            + "Places:\n1. the cave: a dark cave with green crystals and bones\n2. the garden: a palace garden full of flowers and butterflies\n";
    static final String HG_CAST = "Characters:\n1. Vrinda (11 saal): bahadur ladki, firozi ghaghra-choli, lambi choti\n2. Bull: ek bada kala bull (बैल), seengon wala\n3. Raju: chhota bandar (बंदर), lal bandi\n"
            + "Places:\n1. gufa: pahad ki gufa, darwaze par ghanta\n2. bagicha: phoolon wala bada bagicha\n";

    static String title(int i) { return TITLES[i]; }

    static final String[] TITLES = {
            "मीना की तितली (short, Hindi)", "Asha at the cave (short, English)", "Vrinda aur Bull (short, Hinglish)", "राजू का घंटा (short, Hindi)", "Khan's friend (short, English)",
            "Raju ki chhalang (short, Hinglish)", "मीना और खान (short, Hindi)", "The lost sword (short, English)", "Bull ka gussa (short, Hinglish)", "बगीचे की सुबह (short, Hindi)",
            "मीना, राजू और खान की यात्रा (long, Hindi)", "Asha, Raju and the bell (long, English)", "Vrinda ki dosti (long, Hinglish)", "गुफा का रहस्य (long, Hindi)", "The three friends (long, English)",
            "Khan aur Bull (long, Hinglish)", "राजू की चोरी (long, Hindi)", "The brave girl (long, English)", "Do dost aur ek ghanta (long, Hinglish)", "तीन दोस्त और तितली (long, Hindi)"};

    static String[] all() {
        return new String[]{
            // ---- short
            HI_CAST + "मीना की तितली\nदृश्य 1: बगीचे में सुबह\n(स्थान: महल का बगीचा। सुबह का समय है। मीना फूलों के पास खड़ी है।)\n(राजू बंदर दौड़ता हुआ आता है।)\nराजू (हँसते हुए): \"मीना, देखो कितनी सुंदर तितली!\"\nमीना (हैरानी से): \"अरे, यह तो नीली है!\"\n(मीना तितली के पीछे दौड़ती है।)\nराजू (प्यार से): \"धीरे, गिर जाओगी।\"\n(मीना पत्थर पर बैठ जाती है और हँसती है।)\n",
            EN_CAST + "Asha at the cave\nScene 1: At the cave\n(Place: the cave. Evening. Asha walks into the cave with her sword.)\n(Khan comes out of the dark, roaring.)\nKhan (angrily): \"Who dares to enter my cave?\"\nAsha (bravely): \"I am Asha. I am not afraid of you.\"\n(Khan laughs and sits down.)\nKhan (laughing): \"Nobody said that to me before.\"\nAsha (kindly): \"Then let us be friends.\"\n",
            HG_CAST + "Vrinda aur Bull\nScene 1: gufa ke bahar\n(Sthan: gufa. Subah. Vrinda gufa ke bahar khadi hai.)\n(Bull daudta hua aata hai.)\nBull (gusse se): \"Meri gufa se door raho!\"\nVrinda (haste hue): \"Main sirf ghanta dekhne aayi hoon.\"\n(Bull ruk jata hai.)\nBull (udaas hokar): \"Mujhe koi dost nahi hai.\"\nVrinda (pyar se): \"Main tumhari dost banungi.\"\n",
            HI_CAST + "राजू का घंटा\nदृश्य 1: गुफा के दरवाज़े पर\n(स्थान: गुफा। दोपहर। राजू घंटे के नीचे खड़ा है।)\n(मीना चलती हुई आती है।)\nमीना (हैरानी से): \"राजू, यह घंटा किसका है?\"\nराजू (खिलखिलाकर): \"पता नहीं, बजाकर देखते हैं!\"\n(राजू घंटा बजाता है। \"टन-टन\" की आवाज़ गूँजती है।)\n(खान राक्षस गुफा से बाहर आता है।)\nखान (गुस्से से): \"किसने मेरा घंटा बजाया?\"\nमीना (डरते हुए): \"हमने… माफ़ कीजिए।\"\n",
            EN_CAST + "Khan's friend\nScene 1: In the garden\n(Place: the garden. Morning. Raju sits under a tree.)\n(Khan walks in slowly.)\nRaju (surprised): \"A monster in the garden?\"\nKhan (sadly): \"I only wanted to see the flowers.\"\nRaju (kindly): \"Then sit with me. They smell sweet.\"\n(Khan sits down beside Raju. Both laugh.)\n",
            HG_CAST + "Raju ki chhalang\nScene 1: bagicha\n(Sthan: bagicha. Subah. Raju ped par baitha hai.)\n(Vrinda chalti hui aati hai.)\nVrinda (haste hue): \"Raju, neeche aao!\"\n(Raju chhalang lagata hai aur daudta hai.)\nRaju (khush hokar): \"Dekho, main kitna tez hoon!\"\nVrinda (pyar se): \"Bahut tez. Ab chalo, gufa dekhne.\"\n",
            HI_CAST + "मीना और खान\nदृश्य 1: गुफा के अंदर\n(स्थान: गुफा। रात। मीना डरती हुई अंदर आती है।)\n(खान राक्षस अँधेरे से निकलता है।)\nखान (गुस्से से): \"यहाँ क्या कर रही हो?\"\nमीना (रोते हुए): \"मेरा बंदर खो गया है।\"\nखान (धीरे से): \"रोओ मत। मैंने उसे देखा है।\"\n(राजू दौड़ता हुआ आता है। मीना हँसती है।)\n",
            EN_CAST + "The lost sword\nScene 1: In the garden\n(Place: the garden. Afternoon. Asha looks around.)\nAsha (sadly): \"My sword is gone.\"\n(Raju runs in with the sword.)\nRaju (laughing): \"Looking for this?\"\nAsha (angrily): \"Give it back, Raju!\"\n(Raju gives it back. Asha laughs.)\nAsha (happily): \"Thank you, you little thief.\"\n",
            HG_CAST + "Bull ka gussa\nScene 1: gufa\n(Sthan: gufa. Dopahar. Bull gufa ke darwaze par khada hai.)\n(Raju daudta hua aata hai.)\nRaju (haste hue): \"Bull bhai, hato!\"\nBull (gusse se): \"Mujhe bhai mat bolo!\"\n(Vrinda chalti hui aati hai.)\nVrinda (pyar se): \"Dono shaant ho jao. Chalo, bagiche chalte hain.\"\n(Teeno chal padte hain.)\n",
            HI_CAST + "बगीचे की सुबह\nदृश्य 1: महल का बगीचा\n(स्थान: महल का बगीचा। सुबह। मीना और राजू फूलों के बीच खड़े हैं।)\nमीना (खुशी से): \"कितनी सुंदर सुबह है!\"\nराजू (हँसते हुए): \"और कितनी तितलियाँ!\"\n(राजू तितली के पीछे कूदता है।)\nमीना (हँसते हुए): \"रुको, मैं भी आती हूँ।\"\n",
            // ---- long
            HI_CAST + "मीना, राजू और खान की यात्रा\nदृश्य 1: बगीचे में सुबह\n(स्थान: महल का बगीचा। सुबह। मीना फूलों के पास खड़ी है।)\n(राजू बंदर दौड़ता हुआ आता है।)\nराजू (हँसते हुए): \"मीना, आज गुफा चलें?\"\nमीना (डरते हुए): \"गुफा में राक्षस रहता है।\"\nराजू (प्यार से): \"मैं तुम्हारे साथ हूँ।\"\n(मीना मुस्कुराती है। दोनों चल पड़ते हैं।)\nदृश्य 2: गुफा के दरवाज़े पर\n(स्थान: गुफा। दोपहर। मीना और राजू गुफा के दरवाज़े पर आते हैं।)\nमीना (हैरानी से): \"देखो, कितना बड़ा घंटा!\"\n(राजू घंटा बजाता है। \"टन-टन\" की आवाज़ गूँजती है।)\n(खान राक्षस बाहर आता है।)\nखान (गुस्से से): \"किसने मेरा घंटा बजाया?\"\nराजू (डरते हुए): \"मैंने… गलती से।\"\nखान (धीरे से): \"घंटा बजाने वाला मेरा दोस्त बनता है।\"\nमीना (हँसते हुए): \"सच में?\"\nखान (हँसते हुए): \"सच में। अंदर आओ।\"\nदृश्य 3: गुफा के अंदर\n(स्थान: गुफा। शाम। तीनों पत्थरों पर बैठे हैं।)\nमीना (प्यार से): \"तुम्हारी गुफा सुंदर है।\"\nखान (उदास होकर): \"पर यहाँ कोई नहीं आता।\"\nराजू (खिलखिलाकर): \"अब हम रोज़ आएँगे!\"\n(तीनों हँसते हैं।)\nमीना (खुशी से): \"कल बगीचे में मिलते हैं।\"\n(मीना और राजू चलते हुए जाते हैं। खान हाथ हिलाता है।)\n",
            EN_CAST + "Asha, Raju and the bell\nScene 1: In the garden\n(Place: the garden. Morning. Asha stands by the flowers with her sword.)\n(Raju runs in.)\nRaju (laughing): \"Asha, I found a bell in the cave!\"\nAsha (surprised): \"A bell? Whose is it?\"\nRaju (happily): \"Nobody's. Come and see.\"\n(Asha walks after Raju.)\nScene 2: At the cave\n(Place: the cave. Afternoon. Asha and Raju walk up to the cave.)\n(Khan comes out of the dark, roaring.)\nKhan (angrily): \"Who comes to my cave?\"\nAsha (bravely): \"I am Asha. We came for the bell.\"\nKhan (laughing): \"The bell is mine. Take it if you can.\"\n(Asha points her sword. Khan sits down, surprised.)\nAsha (kindly): \"We do not want to fight. We want a friend.\"\nKhan (sadly): \"Nobody wanted that before.\"\nRaju (laughing): \"Then ring the bell for us!\"\n(Khan rings the bell. The sound echoes.)\nScene 3: In the garden\n(Place: the garden. Evening. The three sit on the grass.)\nKhan (happily): \"The flowers are beautiful.\"\nAsha (kindly): \"Come every day.\"\nRaju (laughing): \"And bring the bell!\"\n(All three laugh.)\n",
            HG_CAST + "Vrinda ki dosti\nScene 1: bagicha\n(Sthan: bagicha. Subah. Vrinda phoolon ke paas khadi hai.)\n(Raju daudta hua aata hai.)\nRaju (haste hue): \"Vrinda, gufa chalein?\"\nVrinda (darte hue): \"Wahan Bull rehta hai.\"\nRaju (pyar se): \"Bull achha hai. Chalo.\"\n(Dono chal padte hain.)\nScene 2: gufa ke bahar\n(Sthan: gufa. Dopahar. Vrinda aur Raju gufa ke bahar aate hain.)\n(Bull daudta hua aata hai.)\nBull (gusse se): \"Meri gufa se door raho!\"\nVrinda (haste hue): \"Hum dost banne aaye hain.\"\n(Bull ruk jata hai aur baith jata hai.)\nBull (udaas hokar): \"Mujhe koi dost nahi hai.\"\nRaju (khush hokar): \"Ab hain! Hum teen.\"\nVrinda (pyar se): \"Chalo, ghanta bajate hain.\"\n(Raju ghanta bajata hai. \"Tan-tan\" ki awaaz goonjti hai.)\nScene 3: bagicha\n(Sthan: bagicha. Shaam. Teeno ghaas par baithe hain.)\nBull (khush hokar): \"Phool kitne sundar hain.\"\nVrinda (haste hue): \"Roz aana.\"\nRaju (khilkhilakar): \"Aur ghanta lana!\"\n(Teeno haste hain.)\n",
            HI_CAST + "गुफा का रहस्य\nदृश्य 1: गुफा के दरवाज़े पर\n(स्थान: गुफा। सुबह। मीना और राजू गुफा के दरवाज़े पर खड़े हैं।)\nमीना (हैरानी से): \"अंदर से रोशनी आ रही है।\"\nराजू (डरते हुए): \"हरी रोशनी… कोई राक्षस होगा।\"\nमीना (बहादुरी से): \"चलो देखते हैं।\"\n(दोनों अंदर जाते हैं।)\nदृश्य 2: गुफा के अंदर\n(स्थान: गुफा। दोपहर। हरे पत्थर चमक रहे हैं।)\n(खान राक्षस पत्थर पर बैठा है।)\nखान (उदास होकर): \"कौन है?\"\nमीना (धीरे से): \"हम। तुम उदास क्यों हो?\"\nखान (रोते हुए): \"मेरा घंटा टूट गया।\"\nराजू (प्यार से): \"हम ठीक कर देंगे।\"\n(राजू घंटा ठीक करता है। खान हँसता है।)\nखान (खुशी से): \"धन्यवाद, छोटे दोस्तो!\"\nदृश्य 3: बगीचे में\n(स्थान: महल का बगीचा। शाम। तीनों फूलों के बीच खड़े हैं।)\nमीना (हँसते हुए): \"अब घंटा रोज़ बजेगा।\"\nखान (हँसते हुए): \"और मैं रोज़ आऊँगा।\"\n(राजू तितली के पीछे दौड़ता है।)\n",
            EN_CAST + "The three friends\nScene 1: In the garden\n(Place: the garden. Morning. Raju sits under a tree. Asha walks in.)\nAsha (happily): \"Good morning, Raju.\"\nRaju (laughing): \"Good morning! Khan is coming today.\"\nAsha (surprised): \"The monster? Here?\"\nRaju (kindly): \"He is our friend now.\"\n(Khan walks in slowly.)\nKhan (sadly): \"Am I welcome?\"\nAsha (kindly): \"Of course. Sit with us.\"\n(Khan sits down. The three laugh.)\nScene 2: At the cave\n(Place: the cave. Afternoon. The three walk to the cave.)\nKhan (happily): \"This is my home.\"\nAsha (surprised): \"The crystals are green!\"\nRaju (laughing): \"And the bell is big!\"\n(Raju rings the bell. The sound echoes.)\nKhan (laughing): \"Ring it again!\"\nScene 3: In the garden\n(Place: the garden. Evening. Asha sits on the grass. Khan and Raju stand by the flowers.)\nAsha (kindly): \"Tomorrow we meet again.\"\nKhan (happily): \"Tomorrow.\"\nRaju (laughing): \"With the bell!\"\n",
            HG_CAST + "Khan aur Bull\nScene 1: gufa\n(Sthan: gufa. Subah. Bull gufa ke darwaze par khada hai.)\n(Vrinda chalti hui aati hai.)\nVrinda (haste hue): \"Bull, aaj ek naya dost aayega.\"\nBull (gusse se): \"Mujhe naye dost nahi chahiye.\"\n(Raju daudta hua aata hai.)\nRaju (khush hokar): \"Main hoon naya dost!\"\nBull (hairani se): \"Ek bandar?\"\nVrinda (pyar se): \"Haan. Chalo bagiche chalte hain.\"\nScene 2: bagicha\n(Sthan: bagicha. Dopahar. Teeno phoolon ke beech khade hain.)\nRaju (haste hue): \"Dekho, titli!\"\n(Raju titli ke peeche daudta hai.)\nBull (udaas hokar): \"Main itna tez nahi daud sakta.\"\nVrinda (pyar se): \"Koi baat nahi. Hum saath baithte hain.\"\n(Vrinda aur Bull ghaas par baith jate hain.)\nScene 3: gufa\n(Sthan: gufa. Shaam. Teeno gufa ke andar hain.)\nBull (khush hokar): \"Aaj achha din tha.\"\nRaju (khilkhilakar): \"Kal phir!\"\nVrinda (haste hue): \"Kal phir.\"\n",
            HI_CAST + "राजू की चोरी\nदृश्य 1: बगीचे में सुबह\n(स्थान: महल का बगीचा। सुबह। मीना फूल तोड़ रही है।)\n(राजू चुपके से आता है और मीना का झोला उठा लेता है।)\nमीना (गुस्से से): \"राजू! मेरा झोला दो!\"\nराजू (खिलखिलाकर): \"पकड़ो तो जानें!\"\n(राजू दौड़ता है। मीना उसके पीछे दौड़ती है।)\nदृश्य 2: गुफा के दरवाज़े पर\n(स्थान: गुफा। दोपहर। राजू घंटे के नीचे रुकता है।)\n(खान राक्षस बाहर आता है।)\nखान (गुस्से से): \"यह शोर कैसा है?\"\n(राजू डर कर झोला गिरा देता है।)\nमीना (हाँफते हुए): \"खान, वह मेरा झोला चुराकर भागा है।\"\nखान (हँसते हुए): \"बंदर है, क्या करें।\"\nराजू (रोते हुए): \"माफ़ कर दो, मीना।\"\nमीना (प्यार से): \"ठीक है। पर अब कभी नहीं।\"\nदृश्य 3: बगीचे में\n(स्थान: महल का बगीचा। शाम। तीनों पेड़ के नीचे बैठे हैं।)\nखान (खुशी से): \"चलो, अब सब दोस्त हैं।\"\n(तीनों हँसते हैं।)\n",
            EN_CAST + "The brave girl\nScene 1: In the garden\n(Place: the garden. Morning. Asha practises with her sword.)\n(Raju runs in, scared.)\nRaju (scared): \"Asha! Khan is angry! He is coming!\"\nAsha (bravely): \"Let him come.\"\nScene 2: At the cave\n(Place: the cave. Afternoon. Khan stands at the cave, roaring.)\nKhan (angrily): \"Who took my bell?\"\n(Asha walks up with her sword. Raju hides behind her.)\nAsha (bravely): \"Nobody took it. Look behind you.\"\n(Khan turns and sees the bell. He sits down, surprised.)\nKhan (sadly): \"I am sorry. I was afraid.\"\nAsha (kindly): \"Everybody is afraid sometimes.\"\nRaju (laughing): \"Even monsters!\"\n(Khan laughs.)\nScene 3: In the garden\n(Place: the garden. Evening. The three sit by the flowers.)\nKhan (happily): \"Thank you, brave girl.\"\nAsha (happily): \"Thank you, brave monster.\"\n",
            HG_CAST + "Do dost aur ek ghanta\nScene 1: bagicha\n(Sthan: bagicha. Subah. Vrinda aur Raju phoolon ke paas khade hain.)\nVrinda (haste hue): \"Aaj gufa ka ghanta bajayenge.\"\nRaju (khush hokar): \"Chalo!\"\n(Dono chal padte hain.)\nScene 2: gufa\n(Sthan: gufa. Dopahar. Dono gufa ke darwaze par aate hain.)\n(Bull daudta hua aata hai.)\nBull (gusse se): \"Ghanta mat chhoona!\"\nVrinda (pyar se): \"Sirf ek baar.\"\n(Bull ruk jata hai aur sochta hai.)\nBull (dheere se): \"Theek hai. Ek baar.\"\n(Raju ghanta bajata hai. \"Tan-tan\" ki awaaz goonjti hai. Bull haste hai.)\nBull (haste hue): \"Achha laga!\"\nScene 3: bagicha\n(Sthan: bagicha. Shaam. Teeno ghaas par baithe hain.)\nVrinda (khush hokar): \"Kal phir bajayenge.\"\nBull (khush hokar): \"Kal phir.\"\nRaju (khilkhilakar): \"Kal phir!\"\n",
            HI_CAST + "तीन दोस्त और तितली\nदृश्य 1: बगीचे में सुबह\n(स्थान: महल का बगीचा। सुबह। मीना, राजू और खान फूलों के बीच खड़े हैं।)\nमीना (खुशी से): \"देखो, सुनहरी तितली!\"\nराजू (हँसते हुए): \"मैं पकड़ता हूँ!\"\n(राजू तितली के पीछे दौड़ता है।)\nखान (हँसते हुए): \"धीरे, बंदर!\"\n(राजू गिर जाता है। सब हँसते हैं।)\nदृश्य 2: गुफा के दरवाज़े पर\n(स्थान: गुफा। दोपहर। तितली घंटे पर बैठ जाती है।)\nमीना (धीरे से): \"चुप… वह घंटे पर है।\"\n(खान धीरे से घंटा बजाता है। तितली उड़ जाती है।)\nराजू (उदास होकर): \"उड़ गई।\"\nखान (प्यार से): \"तितलियाँ उड़ने के लिए होती हैं।\"\nमीना (हँसते हुए): \"और दोस्त हँसने के लिए।\"\nदृश्य 3: बगीचे में\n(स्थान: महल का बगीचा। शाम। तीनों पेड़ के नीचे बैठे हैं।)\nमीना (प्यार से): \"कल फिर मिलेंगे।\"\n(तीनों हँसते हैं।)\n",
        };
    }
}
